	-- Tables in the Schema 
	SELECT
		*
	FROM
		PUBLIC."DimCustomers";
	
	SELECT
		*
	FROM
		PUBLIC."FactOrders";
		
	SELECT
		*
	FROM
		PUBLIC."DimCustomers";
	
	SELECT
		*
	FROM
		PUBLIC."DimCustomers";
	
	
	
	-- 1. How many total orders has UrbanCart received so far?
	
	SELECT
		COUNT(*) AS TOTAL_ORDERS
	FROM
		"FactOrders";
	
	-- 2. How many unique customers have placed at least one order?
	SELECT
		COUNT(DISTINCT (CUSTOMER_ID)) AS TOTAL_CUSTOMERS
	FROM
		"FactOrders";
	
	-- 3. Which cities generate the highest number of orders?
	
	SELECT
		DC.CITY,
		COUNT(*) AS NO_OF_ORDERS
	FROM "FactOrders" AS FO
		JOIN "DimCustomers" AS DC ON FO.CUSTOMER_ID = DC.CUSTOMER_ID
	GROUP BY DC.CITY
	ORDER BY count(*) DESC
	LIMIT 1;

	
	-- 4. What percentage of customers have placed more than one order?
	WITH
		REPEAT_CUSTOMERS AS (
			SELECT COUNT(*) AS REPEAT_COUNT
			FROM(
					SELECT
						CUSTOMER_ID
					FROM
						"FactOrders"
					GROUP BY
						CUSTOMER_ID
					HAVING
						COUNT(*) > 1
				) AS SUBQUERY
		),
		TOTAL_CUSTOMERS AS (
			SELECT
				COUNT(DISTINCT (CUSTOMER_ID)) AS TOTAL_COUNTS
			FROM
				"FactOrders"
		) --calculating total customers 
	SELECT
		ROUND(
			(RC.REPEAT_COUNT::NUMERIC / TC.TOTAL_COUNTS) * 100,
			2
		) || ' %' AS REPEAT_RATE_PERCENTAGE
	FROM
		REPEAT_CUSTOMERS RC,
		TOTAL_CUSTOMERS TC;
		
	
	-- 5. What is the monthly trend of total orders over time?
	
	SELECT
	    TO_CHAR(order_date, 'FMMonth''YY') AS order_month,
	    COUNT(*) AS TOTAL_ORDERS
	FROM
	    "FactOrders"
	GROUP BY 1, DATE_TRUNC('month', order_date)
	ORDER BY DATE_TRUNC('month', order_date);


	
	-- 6. What is the total revenue generated by UrbanCart?
	
	SELECT
		SUM(DP.UNIT_PRICE * FOI.QUANTITY) AS TOTAL_REVENUE
	FROM
		"FactOrders" FO
		LEFT JOIN "FactOrderItems" FOI ON FO.ORDER_ID = FOI.ORDER_ID
		LEFT JOIN "DimProducts" DP ON FOI.PRODUCT_ID = DP.PRODUCT_ID;
	
	-- 7. Which product categories contribute the most to total revenue?
	
	SELECT
		DP.CATEGORY,
		SUM(DP.UNIT_PRICE * FOI.QUANTITY) AS TOTAL_REVENUE
	FROM
		"FactOrders" FO
		LEFT JOIN "FactOrderItems" FOI ON FO.ORDER_ID = FOI.ORDER_ID
		LEFT JOIN "DimProducts" DP ON FOI.PRODUCT_ID = DP.PRODUCT_ID
	GROUP BY
		DP.CATEGORY
	ORDER BY
		TOTAL_REVENUE DESC
	LIMIT
		5;
	
	-- 8. Which individual products generate the highest revenue?
	SELECT
		DP.PRODUCT_NAME,
		SUM(DP.UNIT_PRICE * FOI.QUANTITY) AS TOTAL_REVENUE
	FROM
		"FactOrders" FO
		LEFT JOIN "FactOrderItems" FOI ON FO.ORDER_ID = FOI.ORDER_ID
		LEFT JOIN "DimProducts" DP ON FOI.PRODUCT_ID = DP.PRODUCT_ID
	GROUP BY
		DP.PRODUCT_NAME
	ORDER BY
		TOTAL_REVENUE DESC
	LIMIT
		1;
	
	-- 9. What is the average order value (AOV) and Average Basket Size?
	WITH
		NUMBER_OF_ORDERS AS (
			SELECT
				COUNT(*) AS TOTAL_ORDERS
			FROM
				"FactOrders"
		),
		TOTAL_REVENUE AS (
			SELECT
				SUM(DP.UNIT_PRICE * FOI.QUANTITY) AS TOTAL_REVENUE
			FROM
				"FactOrders" FO
				LEFT JOIN "FactOrderItems" FOI ON FO.ORDER_ID = FOI.ORDER_ID
				LEFT JOIN "DimProducts" DP ON FOI.PRODUCT_ID = DP.PRODUCT_ID
		)
		
	SELECT
		ROUND(TOTAL_REVENUE::NUMERIC / TOTAL_ORDERS, 2) AS AVERAGE_ORDER_VALUE
	FROM
		NUMBER_OF_ORDERS,
		TOTAL_REVENUE;
		
	
	WITH
		TOTAL_QUANTITY_OF_ITEMS AS (
			SELECT
				SUM(QUANTITY) AS TOTAL_QUANTITY
			FROM
				PUBLIC."FactOrderItems"
		),
		NUMBER_OF_ORDERS AS (
			SELECT
				COUNT(*) AS TOTAL_ORDERS
			FROM
				"FactOrders"
		)
		
	SELECT
		ROUND(TOTAL_QUANTITY / TOTAL_ORDERS) AS AVERAGE_BUSKET_SIZE
	FROM
		TOTAL_QUANTITY_OF_ITEMS,
		NUMBER_OF_ORDERS;


	
	-- 10. Which products are at risk of stock-out due to high sales volume and low inventory?
	
	SELECT
		PRODUCT_NAME,
		SUM(QUANTITY) AS QUANTITY_SOLD,
		SUM(STOCK) AS STOCK_QUANTITY,
		(SUM(STOCK) - SUM(QUANTITY)) AS ENDING_INVENTORY
		-- quantity
	FROM
		PUBLIC."FactOrderItems" FOI
		LEFT JOIN "DimProducts" DP ON FOI.PRODUCT_ID = DP.PRODUCT_ID
	GROUP BY
		1
	ORDER BY
		ENDING_INVENTORY;

		
	
	-- 11. Which customers contribute the highest total revenue?
	
	SELECT
		FULL_NAME,
		SUM(DP.UNIT_PRICE * FOI.QUANTITY) AS TOTAL_REVENUE
	FROM
		"FactOrders" FO
		LEFT JOIN "FactOrderItems" FOI ON FO.ORDER_ID = FOI.ORDER_ID
		LEFT JOIN "DimProducts" DP ON FOI.PRODUCT_ID = DP.PRODUCT_ID
		LEFT JOIN "DimCustomers" DC ON FO.CUSTOMER_ID = DC.CUSTOMER_ID
	GROUP BY
		FULL_NAME
	ORDER BY
		2 DESC
	LIMIT
		2;
		
	
	-- 12. What is the average number of products purchased per order?

	
	WITH
		TOTAL_QUANTITY_OF_ITEMS AS (
			SELECT
				SUM(QUANTITY) AS TOTAL_QUANTITY
			FROM
				PUBLIC."FactOrderItems"
		),
		NUMBER_OF_ORDERS AS (
			SELECT
				COUNT(*) AS TOTAL_ORDERS
			FROM
				"FactOrders"
		)
	SELECT
		ROUND(TOTAL_QUANTITY / TOTAL_ORDERS) AS AVERAGE_PRODUCT_PER_ORDER
	FROM
		TOTAL_QUANTITY_OF_ITEMS,
		NUMBER_OF_ORDERS;
	
	-- 13.Do male and female customers show different purchasing patterns by category?
	SELECT
		DC.GENDER,
		DP.CATEGORY,
		COUNT(*) AS TOTAL_ORDERS,
		SUM(QUANTITY) AS TOTAL_QUANTITY,
		SUM(DP.UNIT_PRICE * FOI.QUANTITY) AS TOTAL_REVENUE,
		ROUND(AVG(DP.UNIT_PRICE * FOI.QUANTITY)) AS AVG_ORDER_VALUE
	FROM
		"FactOrders" FO
		JOIN "FactOrderItems" FOI ON FO.ORDER_ID = FOI.ORDER_ID
		JOIN "DimProducts" DP ON FOI.PRODUCT_ID = DP.PRODUCT_ID
		JOIN "DimCustomers" DC ON FO.CUSTOMER_ID = DC.CUSTOMER_ID
	GROUP BY
		1,2
	ORDER BY
		1,5 DESC
	
	
	-- 14. Which cities have the highest average order value?
	
	SELECT
		DC.CITY,
		ROUND(
			SUM(DP.UNIT_PRICE * FOI.QUANTITY) / COUNT(DISTINCT (FO.ORDER_ID))
		) AS AVG_ORDER_VALUE
	FROM
		"FactOrders" FO
		JOIN "FactOrderItems" FOI ON FO.ORDER_ID = FOI.ORDER_ID
		JOIN "DimProducts" DP ON FOI.PRODUCT_ID = DP.PRODUCT_ID
		JOIN "DimCustomers" DC ON FO.CUSTOMER_ID = DC.CUSTOMER_ID
	GROUP BY
		1
	ORDER BY
		2 DESC;
	
	-- 15. How does customer purchasing behavior change over time since account creation?
	
	SELECT
		CASE
			WHEN TENURE <= 30 THEN '0 - 1 Month'
			WHEN TENURE <= 90 THEN '1 - 3 Month'
			WHEN TENURE <= 180 THEN '4 - 6 Month'
			WHEN TENURE <= 365 THEN '6 - 12 Month'
			ELSE '12+ Month'
		END AS TENURE_BUCKET,
		ROUND(AVG(TOTAL_REVENUE)) AS AVG_REVENUE
	FROM
		(
			SELECT
				FO.ORDER_ID,
				FO.ORDER_DATE,
				DC.CREATED_AT,
				FO.ORDER_DATE - DC.CREATED_AT AS TENURE,
				SUM(DP.UNIT_PRICE * FOI.QUANTITY) AS TOTAL_REVENUE
			FROM
				"FactOrders" FO
				JOIN "DimCustomers" DC ON FO.CUSTOMER_ID = DC.CUSTOMER_ID
				JOIN "FactOrderItems" FOI ON FO.ORDER_ID = FOI.ORDER_ID
				JOIN "DimProducts" DP ON DP.PRODUCT_ID = FOI.PRODUCT_ID
			GROUP BY
				FO.ORDER_ID,
				FO.ORDER_DATE,
				DC.CREATED_AT
		) AS ORDER_TOTALS
	GROUP BY
		TENURE_BUCKET
	ORDER BY
		MIN(TENURE)

		
		-- 16. Which payment methods are used most frequently?
	SELECT
		"method",
		-- fp.order_id,
		-- foi.quantity,
		SUM(DP.UNIT_PRICE * FOI.QUANTITY) AS TOTAL_REVENUE
	FROM
		"FactPayment" FP
		JOIN "FactOrderItems" FOI ON FP.ORDER_ID = FOI.ORDER_ID
		JOIN "DimProducts" DP ON FOI.PRODUCT_ID = DP.PRODUCT_ID
	GROUP BY
		"method"
	ORDER BY
		2 DESC;
	
	-- 17. Is there any relationship between payment method and order status?
	SELECT
		"method",
		COUNT(
			CASE
				WHEN FO.STATUS = 'Completed' THEN 1
			END
		) * 100 / COUNT(*) || '%' AS COMPELETED_PERCENTAGE,
		COUNT(
			CASE
				WHEN FO.STATUS = 'Cancelled' THEN 1
			END
		) * 100 / COUNT(*) || '%' AS CANCELLED_PERCENTAGE,
		COUNT(
			CASE
				WHEN FO.STATUS = 'Pending' THEN 1
			END
		) * 100 / COUNT(*) || '%' AS PENDING_PERCENTAGE
	FROM
		"FactPayment" FP
		JOIN "FactOrderItems" FOI ON FP.ORDER_ID = FOI.ORDER_ID
		JOIN "DimProducts" DP ON FOI.PRODUCT_ID = DP.PRODUCT_ID
		JOIN "FactOrders" FO ON FO.ORDER_ID = FOI.ORDER_ID
	GROUP BY
		"method" --fo.status
	ORDER BY
		1,2 DESC;
	
	-- 18.Do certain cities prefer specific payment methods?
	SELECT
		"method",
		DC.CITY,
		COUNT(*)
	FROM
		"FactPayment" FP
		JOIN "FactOrderItems" FOI ON FP.ORDER_ID = FOI.ORDER_ID
		JOIN "DimProducts" DP ON FOI.PRODUCT_ID = DP.PRODUCT_ID
		JOIN "FactOrders" FO ON FO.ORDER_ID = FOI.ORDER_ID
		JOIN "DimCustomers" DC ON DC.CUSTOMER_ID = FO.CUSTOMER_ID
	GROUP BY
		1,
		2
	ORDER BY COUNT(*) desc;


-- 19. Are higher-value orders associated with specific payment methods?

	select 
		fo.order_id,
		sum(dp.unit_price* foi.quantity) as order_value,
		fp.method
	from "FactOrders" fo 
	join "FactOrderItems" foi on fo.order_id = foi.order_id 
	join "DimProducts" dp on foi.product_id = dp.product_id 
	join "FactPayment" fp on fp.order_id = fo.order_id

	group by fo.order_id, fp.method
	order by order_value desc


	-- 20. What is the average number of items per order by payment method?
	SELECT
		FP."method",
		round(avg(FOI.QUANTITY),2)
	FROM
		"FactPayment" FP
		JOIN "FactOrderItems" FOI ON FP.ORDER_ID = FOI.ORDER_ID
		JOIN "DimProducts" DP ON FOI.PRODUCT_ID = DP.PRODUCT_ID
		JOIN "FactOrders" FO ON FO.ORDER_ID = FOI.ORDER_ID
		JOIN "DimCustomers" DC ON DC.CUSTOMER_ID = FO.CUSTOMER_ID
	GROUP BY
		FP."method"
	ORDER BY
		2 DESC

		
		-- 21. Which products are most frequently ordered together?
		
	

	
	-- 22. Which product pairs appear most often across all orders?
	SELECT
		-- LEAST(FOI1.PRODUCT_ID, FOI2.PRODUCT_ID) AS PRO1_ID,
		P1.PRODUCT_NAME,
		-- GREATEST(FOI1.PRODUCT_ID, FOI2.PRODUCT_ID) AS PRO2_ID,
		P2.PRODUCT_NAME,
		COUNT(DISTINCT (FOI1.ORDER_ID)) PAIR_BOUGHT
	FROM
		"FactOrderItems" FOI1
		JOIN "FactOrderItems" FOI2 ON FOI1.ORDER_ID = FOI2.ORDER_ID
		AND FOI1.PRODUCT_ID < FOI2.PRODUCT_ID
		JOIN "DimProducts" P1 ON FOI1.PRODUCT_ID = P1.PRODUCT_ID
		JOIN "DimProducts" P2 ON FOI2.PRODUCT_ID = P2.PRODUCT_ID
	GROUP BY
		P1.PRODUCT_NAME,
		P2.PRODUCT_NAME
	ORDER BY
		COUNT(DISTINCT (FOI1.ORDER_ID)) DESC;
	
	-- 23. Are there product pairs that consistently drive higher order values?
	SELECT
		DP1.PRODUCT_NAME AS PRODUCT_1,
		DP2.PRODUCT_NAME AS PRODUCT_2,
		COUNT(*) AS FREQUENCY,
		DP1.UNIT_PRICE AS PRICE_1,
		DP2.UNIT_PRICE AS PRICE_2,
		SUM(DP1.UNIT_PRICE + DP2.UNIT_PRICE) AS PRODUCT_VALUE
	FROM
		"FactOrderItems" FOI1
		JOIN "FactOrderItems" FOI2 ON FOI1.ORDER_ID = FOI2.ORDER_ID
		AND FOI1.PRODUCT_ID < FOI2.PRODUCT_ID
		JOIN "DimProducts" DP1 ON FOI1.PRODUCT_ID = DP1.PRODUCT_ID
		JOIN "DimProducts" DP2 ON FOI2.PRODUCT_ID = DP2.PRODUCT_ID
	GROUP BY
		DP1.PRODUCT_NAME,
		DP2.PRODUCT_NAME,
		DP1.UNIT_PRICE,
		DP2.UNIT_PRICE
	ORDER BY
		PRODUCT_VALUE DESC;
	
	-- 24. Which product combinations could be recommended as bundles to increase revenue?
	SELECT
		P1.PRODUCT_NAME,
		P2.PRODUCT_NAME,
		COUNT(DISTINCT FOI1.ORDER_ID) PAIR_BOUGHT
	FROM
		"FactOrderItems" FOI1
		JOIN "FactOrderItems" FOI2 ON FOI1.ORDER_ID = FOI2.ORDER_ID
		AND FOI1.PRODUCT_ID < FOI2.PRODUCT_ID
		JOIN "DimProducts" P1 ON FOI1.PRODUCT_ID = P1.PRODUCT_ID
		JOIN "DimProducts" P2 ON FOI2.PRODUCT_ID = P2.PRODUCT_ID
	GROUP BY
		P1.PRODUCT_NAME,
		P2.PRODUCT_NAME
	HAVING
		COUNT(DISTINCT FOI1.ORDER_ID) > 10
	ORDER BY
		COUNT(DISTINCT FOI1.ORDER_ID) DESC;
	
	-- 25. Based on product co-occurrence and customer behavior, which products should UrbanCart promote together to maximize cross-selling opportunities?
	WITH
		ORDER_TOTAL AS (
			SELECT
				COUNT(DISTINCT ORDER_ID) TOTALS
			FROM
				"FactOrderItems"
		),
		PRODUCT_ORDERS AS (
			SELECT	
				PRODUCT_ID,
				COUNT(DISTINCT ORDER_ID) PRO_TOTAL
			FROM
				"FactOrderItems"
			GROUP BY
				PRODUCT_ID
		),
		
		PAIR_FREQUENCY AS (
			SELECT
				LEAST(FOI1.PRODUCT_ID, FOI2.PRODUCT_ID) PRO1_ID,
				P1.PRODUCT_NAME PRODUCT1,
				GREATEST(FOI1.PRODUCT_ID, FOI2.PRODUCT_ID) PRO2_ID,
				P2.PRODUCT_NAME PRODUCT2,
				COUNT(DISTINCT FOI1.ORDER_ID) PAIR_BOUGHT
			FROM
				"FactOrderItems" FOI1
				JOIN "FactOrderItems" FOI2 ON FOI1.ORDER_ID = FOI2.ORDER_ID
				AND FOI1.PRODUCT_ID < FOI2.PRODUCT_ID
				JOIN "DimProducts" P1 ON FOI1.PRODUCT_ID = P1.PRODUCT_ID
				JOIN "DimProducts" P2 ON FOI2.PRODUCT_ID = P2.PRODUCT_ID
			GROUP BY
				P1.PRODUCT_NAME,
				P2.PRODUCT_NAME,
				PRO1_ID,
				PRO2_ID
		),
		FINAL_SELECT AS (
			SELECT
				PF.PRO1_ID,
				PF.PRODUCT1,
				PF.PRO2_ID,
				PF.PRODUCT2,
				PF.PAIR_BOUGHT,
				ROUND(
					(
						(PF.PAIR_BOUGHT::FLOAT / OT.TOTALS) / (
							(PO1.PRO_TOTAL::FLOAT / OT.TOTALS) * (PO2.PRO_TOTAL::FLOAT / OT.TOTALS)
						)
					)::NUMERIC,
					2
				) AS LIFT
			FROM
				PAIR_FREQUENCY PF
				CROSS JOIN ORDER_TOTAL OT
				JOIN PRODUCT_ORDERS PO1 ON PO1.PRODUCT_ID = PF.PRO1_ID
				JOIN PRODUCT_ORDERS PO2 ON PO2.PRODUCT_ID = PF.PRO2_ID
			ORDER BY
				LIFT DESC
	)
	SELECT
		*
	FROM
		FINAL_SELECT
	WHERE
		LIFT > 1
	;
	
	
	
	
